import React from 'react';
import Link from 'next/link';
import { permanentRedirect } from 'next/navigation';
import { prisma } from '@/lib/prisma';
import { AboutSection } from '@/components/tools/AboutSection';
import { InstallSection } from '@/components/tools/InstallSection';
import { DownloadButton } from '@/components/tools/DownloadButton';
import { ShareButton } from '@/components/tools/ShareButton';
import { SaveButton } from '@/components/tools/SaveButton';
import { ImageGallery } from '@/components/tools/ImageGallery';
import { SourceNotice } from '@/components/tools/SourceNotice';
import { ToolCard } from '@/components/ui/ToolCard';
import { JsonLd } from '@/components/seo/JsonLd';
import { buildMetadata, graph, breadcrumbSchema, softwareApplicationSchema } from '@/lib/seo';

const glassStyle = {
  background: "rgba(28, 32, 37, 0.4)",
  backdropFilter: "blur(24px)",
  WebkitBackdropFilter: "blur(24px)",
  border: "1px solid rgba(255, 255, 255, 0.05)",
};

const stellarGlowStyle = {
  boxShadow: "0 0 30px rgba(62, 166, 255, 0.1)",
};

interface PageProps {
  params: Promise<{ slug: string }>;
}

async function findTool(identifier: string) {
  return prisma.tool.findFirst({
    where: {
      OR: [
        { slug: { equals: identifier } },
        { id: identifier },
        { repoUrl: { contains: `/${identifier}` } },
      ],
    },
    include: {
      platforms: true,
      toolTypes: true,
      // Uploader — powers the "Uploaded by …" trust attribution.
      user: { select: { name: true, role: true, isPrimaryAdmin: true } },
    },
  });
}

export async function generateMetadata({ params }: PageProps) {
  const { slug } = await params;
  const tool = await findTool(slug);

  if (!tool) {
    return buildMetadata({
      title: "Tool Not Found",
      index: false,
    });
  }

  const proprietary = tool.sourceType === "PROPRIETARY";

  return buildMetadata({
    // Curator-authored SEO title wins; otherwise a neutral, non-overclaiming
    // default (not everything in the directory is an "AI tool" or open source).
    title:
      tool.metaTitle?.trim() ||
      `${tool.name} — ${proprietary ? "Tool Review & Guide" : "Open-Source Tool"}`,
    // Curator override first, then the short description, then about text.
    description:
      tool.metaDescription ||
      tool.description ||
      tool.aboutText ||
      (proprietary
        ? `Discover ${tool.name}, a curated AI tool. Not open source — reviewed and listed for usefulness.`
        : `Discover ${tool.name}, a curated open-source AI tool.`),
    // Canonical is ALWAYS the slug URL — the sole public identifier for a tool.
    path: tool.slug ? `/tools/${tool.slug}` : `/tools/${slug}`,
    // og:image is generated by opengraph-image.tsx (branded 1200×630).
    image: null,
    // Index only ACTIVE tools that have a slug; drafts/soft-deleted and any
    // legacy slug-less rows stay out of search (they have no canonical URL).
    index: tool.status === "ACTIVE" && !!tool.slug,
  });
}

export default async function ToolDetailPage({ params }: PageProps) {
  const resolvedParams = await params;
  const toolSlug = resolvedParams.slug;

  // Query tool dynamically by slug (with id / repo fallbacks for old links)
  const dbTool = await findTool(toolSlug);

  // Consolidate to the canonical slug URL: any access via id or repo path
  // 301-redirects to /tools/<slug> so search engines index one URL only.
  if (dbTool?.slug && toolSlug !== dbTool.slug) {
    permanentRedirect(`/tools/${dbTool.slug}`);
  }

  if (!dbTool) {
    return (
      <main className="min-h-screen bg-[#0e0e0e] flex flex-col items-center justify-center text-white px-4">
        <div className="glass-panel p-8 rounded-2xl max-w-md w-full text-center space-y-6 border border-outline-variant/30">
          <span className="material-symbols-outlined text-6xl text-primary-container block">warning</span>
          <h1 className="font-headline-md text-2xl">Tool Not Found</h1>
          <p className="text-on-surface-variant text-sm font-body-base leading-relaxed">
            The requested tool <code className="bg-[#1c2025] px-2 py-1 rounded text-xs">{toolSlug}</code> is not present in our database. It might have been removed or never submitted.
          </p>
          <div className="flex flex-col gap-3">
            <Link href="/tools" className="bg-primary-container text-on-primary-container px-6 py-3 rounded-full font-label-sm hover:bg-primary-container/80 transition-colors">
              EXPLORE INDEX
            </Link>
            <Link href="/" className="text-on-surface-variant hover:text-white transition-colors text-xs font-semibold">
              Go Home
            </Link>
          </div>
        </div>
      </main>
    );
  }

  // Bind dynamic details from database
  // Golden Rule: Strict adherence to existing data without fallbacks
  const installCommand = dbTool.installCommand || "";
  const aboutText = dbTool.aboutText || dbTool.description || "No description provided.";
  const author = dbTool.author;
  const since = dbTool.since;
  const license = dbTool.license;
  const version = dbTool.version;
  const website = dbTool.websiteUrl;
  const downloadUrl = dbTool.downloadUrl;

  const formattedStars = dbTool.stars >= 1000 
    ? (dbTool.stars / 1000).toFixed(1).replace(/\.0$/, '') + 'k'
    : dbTool.stars.toString();

  const formattedForks = dbTool.forks >= 1000 
    ? (dbTool.forks / 1000).toFixed(1).replace(/\.0$/, '') + 'k'
    : dbTool.forks.toString();

  // Listing kind. Proprietary tools carry a disclosure notice, drop their
  // (meaningless) repo stats, and swap the brand accent for amber so the two
  // kinds stay tellable apart at a glance across the whole site.
  const isProprietary = dbTool.sourceType === 'PROPRIETARY';
  // The one public link that always exists: repo for OSS, website otherwise.
  const primaryUrl = isProprietary ? (website || dbTool.repoUrl) : (dbTool.repoUrl || website);

  const categoryLabel = dbTool.toolTypes[0]?.name || (isProprietary ? 'TOOL' : 'OPEN SOURCE TOOL');

  // Parse JSON fields
  let features: {title: string, description: string, icon: string}[] = [];
  try {
    if (dbTool.features) features = JSON.parse(dbTool.features);
  } catch (e) {}

  // The admin form always serialises exactly 3 feature slots, so an untouched
  // form stores 3 blank ones. Drop them, or the Capability card renders as a
  // column of bare icons.
  features = features.filter((f) => f?.title?.trim());

  if (features.length === 0) {
    // The fallback must never assert something untrue — a proprietary tool is
    // not "community audited".
    features = isProprietary
      ? [
          { title: 'Hand-picked', description: 'Listed because our editors judged it genuinely useful.', icon: 'bolt' },
          { title: 'Vetted Quality', description: 'Curated by the AI Tool Research review team.', icon: 'lock' },
          { title: 'Closed Source', description: 'The source is not public — the vendor controls the code and your data.', icon: 'extension' }
        ]
      : [
          { title: 'Open Source', description: '100% community audited and freely modifiable code.', icon: 'bolt' },
          { title: 'Vetted Quality', description: 'Curated by the AI Tool Research developer review team.', icon: 'lock' },
          { title: 'Extensible', description: 'Easily pluggable with custom plugins or standard pipelines.', icon: 'extension' }
        ];
  }

  let images: string[] = [];
  try {
    if (dbTool.galleryImages) images = JSON.parse(dbTool.galleryImages);
  } catch (e) {}

  // Fallback to a placeholder if no images and no hero
  if (images.length === 0 && !dbTool.heroImageUrl) {
    images = ["https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=800&q=80"];
  }

  const imageRatio = dbTool.galleryLayout === '9:16' ? '9:16' : '16:9';

  // Fetch related tools (sharing toolTypes/platforms or general active tools)
  const relatedToolsRaw = await prisma.tool.findMany({
    where: {
      status: 'ACTIVE',
      id: { not: dbTool.id },
      ...(dbTool.toolTypes.length > 0
        ? {
            toolTypes: {
              some: {
                name: { in: dbTool.toolTypes.map((t: any) => t.name) },
              },
            },
          }
        : {}),
    },
    take: 8,
    include: {
      platforms: true,
      toolTypes: true,
    },
    orderBy: [
      { stars: 'desc' },
      { createdAt: 'desc' },
    ],
  });

  let relatedTools = relatedToolsRaw;
  if (relatedTools.length < 4) {
    const extraTools = await prisma.tool.findMany({
      where: {
        status: 'ACTIVE',
        id: { notIn: [dbTool.id, ...relatedTools.map((t) => t.id)] },
      },
      take: 8 - relatedTools.length,
      include: {
        platforms: true,
        toolTypes: true,
      },
      orderBy: [
        { stars: 'desc' },
        { createdAt: 'desc' },
      ],
    });
    relatedTools = [...relatedTools, ...extraTools];
  }

  const formattedRelatedTools = relatedTools.map((tool) => {
    const formattedStars = tool.stars >= 1000
      ? (tool.stars / 1000).toFixed(1).replace(/\.0$/, '') + 'k'
      : tool.stars.toString();
    const tags = [
      ...tool.platforms.map((p: any) => p.name),
      ...tool.toolTypes.map((t: any) => t.name),
    ];
    return {
      id: tool.id,
      slug: tool.slug || tool.id,
      name: tool.name,
      stars: formattedStars,
      description: tool.description || '',
      tags,
      icon: tool.toolTypes[0]?.name?.toLowerCase() || 'build',
      color: tool.sourceType === 'PROPRIETARY' ? 'bg-amber-500/10 text-[#D9A441]' : 'bg-primary-container/10 text-primary-container',
      logoUrl: tool.heroImageUrl || tool.imageUrl || null,
      sourceType: tool.sourceType,
    };
  });

  const metadataCardElement = (
    <div 
      className="p-6 rounded-2xl flex flex-col justify-between space-y-4"
      style={{ ...glassStyle, ...stellarGlowStyle, backgroundColor: "rgba(10, 10, 15, 0.7)" }}
    >
      <div className="flex justify-between items-center py-2 border-b border-outline-variant/30 text-sm">
        <span className="text-on-surface-variant">Source</span>
        <span className={`font-bold ${isProprietary ? 'text-[#D9A441]' : 'text-on-surface'}`}>
          {isProprietary ? 'Proprietary' : 'Open source'}
        </span>
      </div>
      {author && (
        <div className="flex justify-between items-center py-2 border-b border-outline-variant/30 text-sm">
          <span className="text-on-surface-variant">Author</span>
          <span className="text-on-surface font-bold">{author}</span>
        </div>
      )}
      {since && (
        <div className="flex justify-between items-center py-2 border-b border-outline-variant/30 text-sm">
          <span className="text-on-surface-variant">Since</span>
          <span className="text-on-surface font-bold">{since}</span>
        </div>
      )}
      {license && (
        <div className="flex justify-between items-center py-2 border-b border-outline-variant/30 text-sm">
          <span className="text-on-surface-variant">License</span>
          <span className="text-on-surface font-bold">{license}</span>
        </div>
      )}
      {version && (
        <div className="flex justify-between items-center py-2 border-b border-outline-variant/30 text-sm">
          <span className="text-on-surface-variant">Version</span>
          <span className="text-on-surface font-bold">{version}</span>
        </div>
      )}
      
      {dbTool.platforms.length > 0 && (
        <div className="flex justify-between items-start gap-3 py-2 border-b border-outline-variant/30 text-sm">
          <span className="text-on-surface-variant shrink-0 pt-0.5">OS</span>
          <div className="flex flex-wrap justify-end gap-1.5">
            {dbTool.platforms.map((p: any) => (
              <span key={p.name} className="bg-on-surface-variant/10 text-on-surface-variant px-2.5 py-0.5 rounded-full text-[10px] font-bold border border-outline-variant/30 tracking-wider">
                {p.name.toUpperCase()}
              </span>
            ))}
          </div>
        </div>
      )}

      {website && (
        <div className="flex justify-between items-center py-2 text-sm">
          <span className="text-on-surface-variant">Website</span>
          <a 
            href={website} 
            target="_blank" 
            rel="noopener noreferrer"
            className="text-primary hover:underline font-bold truncate max-w-[200px] text-right"
          >
            {website}
          </a>
        </div>
      )}
    </div>
  );

  return (
    <main className="max-w-[1280px] mx-auto px-4 md:px-6 pt-24 pb-12">
      {dbTool.status === 'ACTIVE' && dbTool.slug && (
        <JsonLd
          data={graph(
            softwareApplicationSchema({
              name: dbTool.name,
              description: dbTool.metaDescription || dbTool.description,
              // Slug-only URL — must match the canonical set in generateMetadata.
              path: `/tools/${dbTool.slug}`,
              image: dbTool.heroImageUrl || dbTool.imageUrl,
              operatingSystems: dbTool.platforms.map((p: any) => p.name),
              category: dbTool.toolTypes[0]?.name,
              repoUrl: dbTool.repoUrl,
            }),
            breadcrumbSchema([
              { name: 'Home', path: '/' },
              { name: 'Tools', path: '/tools' },
              { name: dbTool.name, path: `/tools/${dbTool.slug}` },
            ]),
          )}
        />
      )}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        
        {/* Left Column (Main) */}
        <div className="lg:col-span-8 space-y-6">
          
          {/* Hero Section */}
          <div 
            className="relative rounded-xl overflow-hidden mb-8 border border-white/5 bg-[#09090b] min-h-[290px] flex flex-col"
            style={stellarGlowStyle}
          >
            {/* Blurred background image to simulate extracting colors from logo */}
            {(dbTool.heroImageUrl || dbTool.imageUrl) && (
              <div
                className="absolute inset-0 opacity-60 blur-[100px] scale-150 saturate-200 brightness-50 mix-blend-screen"
                style={{
                  backgroundImage: `url(${dbTool.heroImageUrl || dbTool.imageUrl})`,
                  backgroundSize: 'cover',
                  backgroundPosition: 'center',
                }}
              />
            )}

            {/* Ambient bottom glow matching the reference image */}
            <div className="absolute -bottom-32 left-1/2 -translate-x-1/2 w-[80%] h-64 bg-indigo-500/15 blur-[80px] rounded-full pointer-events-none"></div>
            <div className="absolute -bottom-32 left-1/2 -translate-x-1/2 w-[40%] h-64 bg-purple-500/10 blur-[60px] rounded-full pointer-events-none"></div>
            
            {/* Dark overlay for readability */}
            <div className="absolute inset-0 bg-[#09090b]/70 backdrop-blur-[10px]"></div>

            {/* Save + Share — top-right of the hero card */}
            <div className="absolute top-4 right-4 md:top-6 md:right-6 z-20 flex items-center gap-2">
              <SaveButton toolId={dbTool.id} variant="hero" />
              <ShareButton title={dbTool.name} text={dbTool.description} />
            </div>

            <div className="relative p-6 md:p-8 z-10 flex-grow flex flex-col justify-start">
              <div className="flex items-center gap-3 mb-4 pr-24 md:pr-28">
                <div 
                  className="flex gap-2 overflow-hidden whitespace-nowrap"
                  style={{ 
                    maskImage: "linear-gradient(to right, black 85%, transparent 100%)", 
                    WebkitMaskImage: "-webkit-linear-gradient(left, black 85%, transparent 100%)" 
                  }}
                >
                  {dbTool.toolTypes.map((t: any) => (
                    <span key={t.name} className="bg-primary-container/10 text-primary-container px-3 py-1 rounded-full text-[10px] font-bold border border-primary-container/20 tracking-wider shrink-0">
                      {t.name.toUpperCase()}
                    </span>
                  ))}
                </div>
              </div>
              <div className="flex items-center gap-3 md:gap-4 mb-2 mt-2 md:mt-0">
                {(dbTool.heroImageUrl || dbTool.imageUrl) && (
                  <img
                    src={dbTool.heroImageUrl || dbTool.imageUrl || ''}
                    alt={`${dbTool.name} logo`}
                    className="h-10 md:h-16 w-auto object-contain rounded-lg drop-shadow-xl shrink-0"
                  />
                )}
                <h1 className="font-sans text-2xl md:text-5xl text-white tracking-tighter font-black drop-shadow-xl">
                  {dbTool.name}
                </h1>
                {/* Verified curation mark — blue tick beside the tool name,
                    signalling a human-vetted listing (Twitter/Facebook style). */}
                <span
                  role="img"
                  aria-label="Verified tool"
                  title="Verified — human-curated listing"
                  className="material-symbols-outlined shrink-0 -ml-1 self-center !text-[15px] md:!text-[22px] drop-shadow-xl leading-none"
                  style={{ color: '#1D9BF0', fontVariationSettings: "'FILL' 1" }}
                >
                  verified
                </span>
              </div>
              <p className="text-white font-sans max-w-2xl text-base md:text-lg leading-relaxed font-semibold drop-shadow-xl">
                {dbTool.description}
              </p>
              {/* Repo stats, or — for a tool with no repo — an honest statement
                  of what it is instead of a row of zeroes. */}
              <div className="flex items-center gap-4 mt-8 bg-black/60 backdrop-blur-xl w-fit px-5 py-2.5 rounded-full border border-white/20 shadow-lg">
                {isProprietary ? (
                  <span className="text-white flex items-center gap-1.5 text-sm font-bold drop-shadow-md">
                    <span className="material-symbols-outlined text-[#D9A441] text-base drop-shadow-md">lock</span>
                    Proprietary · no public repo
                  </span>
                ) : (
                  <>
                    <span className="text-white flex items-center gap-1.5 text-sm font-bold drop-shadow-md">
                      <span className="material-symbols-outlined text-yellow-400 text-base drop-shadow-md">star</span>
                      {formattedStars} Stars
                    </span>
                    <span className="text-white flex items-center gap-1.5 text-sm font-bold drop-shadow-md">
                      <span className="material-symbols-outlined text-gray-300 text-base drop-shadow-md">fork_right</span>
                      {formattedForks} Forks
                    </span>
                  </>
                )}
              </div>

              {/* Action Buttons */}
              {/* Action Buttons */}
              <div className="flex flex-wrap items-center gap-3 mt-auto pt-8">
                {/* Primary link — the repo for an open-source tool, the vendor's
                    site for a proprietary one. Rendered only if one exists. */}
                {primaryUrl && (
                <a
                  href={primaryUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center justify-between gap-4 bg-white/20 backdrop-blur-xl border border-white/30 text-white pl-5 pr-2 py-2 rounded-full font-sans font-bold text-sm hover:bg-white/30 hover:scale-[1.02] transition-all shadow-2xl w-fit group"
                >
                  <span className="tracking-wide lowercase font-semibold drop-shadow-sm">{isProprietary ? 'visit website' : 'view repo'}</span>
                  <div className={`${isProprietary ? 'bg-[#D9A441]' : 'bg-[#ffa6ff]'} text-black w-7 h-7 rounded-full flex items-center justify-center group-hover:opacity-90 transition-opacity`}>
                    <svg width="14" height="14" viewBox="0 0 14 14" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                      <circle cx="2" cy="7" r="1.2" />
                      <circle cx="5" cy="7" r="1.2" />
                      <circle cx="8" cy="7" r="1.2" />
                      <circle cx="11" cy="7" r="1.2" />
                      <circle cx="8" cy="4" r="1.2" />
                      <circle cx="5" cy="1.5" r="1.2" />
                      <circle cx="8" cy="10" r="1.2" />
                      <circle cx="5" cy="12.5" r="1.2" />
                    </svg>
                  </div>
                </a>
                )}

                {/* Download Button — single asset → direct link, multiple → chooser modal */}
                <DownloadButton
                  downloadUrl={downloadUrl}
                  downloadAssets={dbTool.downloadAssets}
                  repoUrl={dbTool.repoUrl}
                />
              </div>
            </div>
          </div>

          {/* Disclosure — sits between the hero and the write-up so it is read
              before any of the editorial copy. */}
          {isProprietary && <SourceNotice toolName={dbTool.name} note={dbTool.sourceNote} />}

          {/* Description Section - Interactive Client Island */}
          <AboutSection aboutText={aboutText} />

          {/* Images Gallery Section */}
          {images && images.length > 0 && (
            <section className="space-y-4">
              <h3 className="font-headline-md text-base md:text-lg text-on-surface flex items-center gap-2">
                <span className="material-symbols-outlined text-primary-container text-xl">gallery_thumbnail</span>
                Gallery
              </h3>

              <ImageGallery images={images} imageRatio={imageRatio} toolName={dbTool.name} />
            </section>
          )}

          {/* Mobile Metadata Card — rendered right under the pictures on mobile */}
          <div className="block lg:hidden">
            {metadataCardElement}
          </div>

          {/* Installation Section - Interactive Client Island */}
          <InstallSection toolName={dbTool.name} installCommand={installCommand} />

          {/* Similar & Recommended Tools Section — 1 horizontal row */}
          {formattedRelatedTools.length > 0 && (
            <section className="space-y-4 pt-2">
              <div className="flex items-center justify-between">
                <h3 className="font-headline-md text-base md:text-lg text-on-surface flex items-center gap-2">
                  <span className="material-symbols-outlined text-primary-container text-xl">auto_awesome</span>
                  Similar & Recommended Tools
                </h3>
                <Link href="/tools" className="text-xs font-semibold text-primary hover:underline flex items-center gap-1">
                  View All
                  <span className="material-symbols-outlined text-sm">arrow_forward</span>
                </Link>
              </div>
              <div className="overflow-x-auto pb-4 scrollbar-thin scrollbar-thumb-white/10">
                <div className="flex gap-4 min-w-max">
                  {formattedRelatedTools.map((tool) => (
                    <div key={tool.id} className="w-[280px] sm:w-[320px] shrink-0">
                      <ToolCard {...tool} />
                    </div>
                  ))}
                </div>
              </div>
            </section>
          )}

        </div>

        {/* Right Column (Sidebar) */}
        <div className="lg:col-span-4">
          <div className="lg:sticky lg:top-1/2 lg:-translate-y-1/2 space-y-6">

            {/* Desktop Metadata Card */}
            <div className="hidden lg:block">
              {metadataCardElement}
            </div>

            {/* Capability Card */}
            <div className="p-6 rounded-2xl space-y-4" style={{ ...glassStyle, backgroundColor: "rgba(10, 10, 15, 0.7)" }}>
              <h3 className="font-headline-md text-on-surface text-lg">Capability</h3>
              <div className="flex flex-col gap-4">
                {features.map((feature, i) => (
                  <div key={i} className="flex gap-3 items-start">
                    <div className="w-8 h-8 rounded-full bg-primary-container/10 flex items-center justify-center text-primary-container shrink-0">
                      <span className="material-symbols-outlined text-base">{feature.icon}</span>
                    </div>
                    <div>
                      <div className="text-on-surface text-sm font-bold">{feature.title}</div>
                      <div className="text-xs text-on-surface-variant leading-relaxed mt-0.5">{feature.description || (feature as any).desc}</div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
            
          </div>
        </div>
      </div>
    </main>
  );
}
